### PR TITLE
Add 0.12 tensforflow compatiblity

### PR DESCRIPTION
**Pull request by frk2**
-  since they changed arg ordering for tf.split and tf.concat to be more numpy-like according to:
https://github.com/tensorflow/tensorflow/issues/6501

If you guys have a better more pythonic solution please feel free to disregard this PR! I'm a noob in python so maybe theres a cooler way to version check here :sunglasses: :

### CODE REVIEW

**Comment by Brok-Bucholtz** [comment]
Thanks for spotting this.  However, a few changes need to be made:
- `tf.split` has been changed in version r1.0, not 0.12.  Please change the PR to reflect this.
- `tf.concat` is will generate a deprecated error in version r1.0

**Comment by frk2** [comment]
Done. My version currently says '0.12-head' and I have the above parameter mods. I've made it do > 0.12 (instead of >= 0.12) to take care of this.

interesting - tf.concat fails for me in 0.12-head due to wrong parameters placement. Are you saying that the function tf.concat itself has been deprecated?

**Comment by mvirgo** [comment]
Looks like Dom ended up making a similar change in Feb '17 - thanks though Faraz :)

**Comment by frk2** [comment]
:bowing_man:

**Pull request closed without merging**
